#! /bin/bash

echo "Ranking your mirrors. Please Wait.....


"
sudo apt-get install netselect-apt -qq -y
sudo netselect-apt testing --nonfree -o /etc/apt/sources.list


echo "

Updating your system.....

"
sudo apt-get update && sudo apt-get upgrade -qq -y


echo "
Installing Desktop Environment as you wanted....

"
sudo apt-get install xfce4 gdebi hardinfo htop mugshot synaptic \
vlc intel-microcode lightdm-gtk-greeter seahorse neofetch xfce4-terminal -qq -y

sudo apt purge --autoremove xterm -y

echo "


Do you want to configure lightdm for auto login now?"
select yn in "Yes, I want to." "I will do it later"; do
case $yn in
Yes, I want to. ) sudo nano /etc/lightdm/lightdm.conf; break;;
I will do it later ) echo "okay!"
exit;;
esac
done
